podTemplate (
    containers: [
        containerTemplate(name: 'nodejs', image: "node:12-alpine", ttyEnabled: true, command: 'cat')
    ]
) {
    node(POD_LABEL) {
        stage('git') {
            container('nodejs') {
                sh 'echo hello world'
                checkout scm
            }
        }
        stage('npm install') {
            container('nodejs') {
                sh 'npm install'
            }
        }
        stage('npm build') {
            container('nodejs') {
                sh 'npm run build'
            }
        }
    }
}