apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins